defaults:
  # - override hydra/launcher: submitit_slurm
  - _self_


MODEL_NAME: 'bert-base-uncased'
MAX_LENGTH: 128
BATCH_SIZE: 512
EPOCHS: 20
LEARNING_RATE: 2e-5
DEVICE: 0
SAVED_DATA_DIR: '/home/kbhau001/llm/tokenized_data' 
DATASET_NAME: 'ag_news'
USE_LOGGER: False
PROJECT_NAME: 'cvi-tracking'

TRAIN_SUBSET_RATIO: 0.1
TEST_SUBSET_RATIO: 0.5

hydra:
  job:
    chdir: True